#ifndef _ACTIVITY_H_
#define _ACTIVITY_H_

#include <string>
#include <fstream>
#include <chrono>
#include <iomanip>

class Activity {
private:
    std::string start_time, end_time, checkin_time, checkout_time; // Y-M-D-H-M-S
    std::string position, checkin_position, checkout_position;
    std::string title, introduction, detail;
    std::string participant_number, participant_condition, reward;
    std::string signup_url, checkin_url, checkout_url;
    
    int id;

public:
    // construct with id from outside
    Activity(
        int id = 0,
        std::string title = "",
        std::string introduction = "",
        std::string detail = "",
        std::string start_time = "",
        std::string end_time = "",
        std::string position = "",
        std::string checkin_time = "",
        std::string checkout_time = "",
        std::string checkin_position = "",
        std::string checkout_position = "",
        std::string participant_number = "",
        std::string participant_condition = "",
        std::string reward = "",
        std::string signup_url = "",
        std::string checkin_url = "",
        std::string checkout_url = ""
        ): start_time(start_time),
          end_time(end_time),
          checkin_time(checkin_time),
          checkout_time(checkout_time),
          position(position),
          checkin_position(checkin_position),
          checkout_position(checkout_position),
          title(title),
          introduction(introduction),
          detail(detail),
          participant_number(participant_number),
          participant_condition(participant_condition),
          reward(reward),
          signup_url(signup_url),
          checkin_url(checkin_url),
          checkout_url(checkout_url),
          id(id)
        {}
    
    //construct with id generated by time
    static long long generateId() {
        using namespace std::chrono;
        auto now = system_clock::now();
        std::time_t t = system_clock::to_time_t(now);
        std::tm tm{};
    #if defined(_WIN32)
        localtime_s(&tm, &t);
    #else
        localtime_r(&t, &tm);
    #endif
        std::ostringstream oss;
        oss << std::put_time(&tm, "%Y%m%d%H%M%S");
        return std::stoll(oss.str());
}
    
    // construct with id generated by time
    Activity(
        std::string title = "",
        std::string introduction = "",
        std::string detail = "",
        std::string start_time = "",
        std::string end_time = "",
        std::string position = "",
        std::string checkin_time = "",
        std::string checkout_time = "",
        std::string checkin_position = "",
        std::string checkout_position = "",
        std::string participant_number = "",
        std::string participant_condition = "",
        std::string reward = "",
        std::string signup_url = "",
        std::string checkin_url = "",
        std::string checkout_url = ""
        ): start_time(start_time),
          end_time(end_time),
          checkin_time(checkin_time),
          checkout_time(checkout_time),
          position(position),
          checkin_position(checkin_position),
          checkout_position(checkout_position),
          title(title),
          introduction(introduction),
          detail(detail),
          participant_number(participant_number),
          participant_condition(participant_condition),
          reward(reward),
          signup_url(signup_url),
          checkin_url(checkin_url),
          checkout_url(checkout_url),
          id(generateId())
        {}
    
    Activity(const nlohmann::json& j);  // initialize from json string
    std::string toString();
    bool save();
    bool read(int ID);
    bool del();
    int getId();
};

#endif
