#ifndef _ACTIVITY_H_
#define _ACTIVITY_H_

#include <string>
#include <fstream>
#include <chrono>

class Activity {
private:
    std::string start_time, end_time, checkin_time, checkout_time; // Y-M-D-H-M-S
    std::string position, checkin_position, checkout_position;
    std::string title, introduction, detail;
    std::string participant_number, participant_condition, reward;
    std::string signup_url, checkin_url, checkout_url;
    
    int id;

public:
    // construct with id from outside
    Activity(
        int id = 0,
        std::string title = "",
        std::string introduction = "",
        std::string detail = "",
        std::string start_time = "",
        std::string end_time = "",
        std::string position = "",
        std::string checkin_time = "",
        std::string checkout_time = "",
        std::string checkin_position = "",
        std::string checkout_position = "",
        std::string participant_number = "",
        std::string participant_condition = "",
        std::string reward = "",
        std::string signup_url = "",
        std::string checkin_url = "",
        std::string checkout_url = ""
        ): start_time(start_time),
          end_time(end_time),
          checkin_time(checkin_time),
          checkout_time(checkout_time),
          position(position),
          checkin_position(checkin_position),
          checkout_position(checkout_position),
          title(title),
          introduction(introduction),
          detail(detail),
          participant_number(participant_number),
          participant_condition(participant_condition),
          reward(reward),
          signup_url(signup_url),
          checkin_url(checkin_url),
          checkout_url(checkout_url),
          id(id)
        {}
    
    //construct with id generated by time
    static int generateId() {
        using namespace std::chrono;
        return duration_cast<milliseconds>(
            system_clock::now().time_since_epoch()
        ).count();
    }
    
    // construct with id generated by time
    Activity(
        std::string title = "",
        std::string introduction = "",
        std::string detail = "",
        std::string start_time = "",
        std::string end_time = "",
        std::string position = "",
        std::string checkin_time = "",
        std::string checkout_time = "",
        std::string checkin_position = "",
        std::string checkout_position = "",
        std::string participant_number = "",
        std::string participant_condition = "",
        std::string reward = "",
        std::string signup_url = "",
        std::string checkin_url = "",
        std::string checkout_url = ""
        ): start_time(start_time),
          end_time(end_time),
          checkin_time(checkin_time),
          checkout_time(checkout_time),
          position(position),
          checkin_position(checkin_position),
          checkout_position(checkout_position),
          title(title),
          introduction(introduction),
          detail(detail),
          participant_number(participant_number),
          participant_condition(participant_condition),
          reward(reward),
          signup_url(signup_url),
          checkin_url(checkin_url),
          checkout_url(checkout_url),
          id(generateId())
        {}
    
    Activity(const nlohmann::json& j);  // initialize from json string
    std::string toString();
    bool save();
    bool read(int ID);
    int getId();
};

#endif
